### ISSUE TITLE
CrazyAra ignoring my UCI "Threads" option

### ISSUE THREAD

**Issue by ProgramFOX** [QueensGambit/CrazyAra-Engine#4]
Because the CUDA version with `cpu` as `Context` did already work so far, I decided to try that already. I set the number of threads to use to one (same problem appears when picking 2 threads, didn't test for other values).

```
uci
setoption name Context value cpu
setoption name Threads value 1
isready
go movetime 5000
```

![Screenshot from 2019-08-27 21-50-53](https://user-images.githubusercontent.com/8034604/63803255-ca2d3500-c914-11e9-8054-8eb7c2fa0997.png)

As confirmed with both htop and the System Monitor, CrazyAra takes up 100% of _all my cores_ when thinking of a move, but that really shouldn't happen if I only specify one thread.

**Comment by QueensGambit** [comment]
Yes, that phenomena probably needs further explanation.
_CrazyAra_ will only use one thread for the MCTS tree management and tree traversal if `Threads` is set to 1.
However, the MXNet library will require as many threads as there are available on the system.
You need to set `MXNET_OMP_MAX_THREADS` and maybe also `MXNET_CPU_PRIORITY_NTHREADS` and `MXNET_CPU_NNPACK_NTHREADS` to 1 in order to only use one thread for the neural network inference.

The neural network inference  requires the majority of the computational effort, especially for deeper more complex models.

Further information can be found here: 
* https://mxnet.incubator.apache.org/versions/master/faq/env_var.html

**Comment by ProgramFOX** [comment]
Ah yes, setting those and `OMP_NUM_THREADS` to 1 did the trick.
